// Code generated by Thrift Compiler (0.16.0). DO NOT EDIT.

package trpc

import (
	"bytes"
	"context"
	"fmt"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

// Attributes:
//  - Type
//  - Content
//  - ShardingId
//  - Trace
type TRequest struct {
  Type *int32 `thrift:"Type,1" db:"Type" json:"Type,omitempty"`
  Content []byte `thrift:"Content,2" db:"Content" json:"Content,omitempty"`
  ShardingId *int64 `thrift:"ShardingId,3" db:"ShardingId" json:"ShardingId,omitempty"`
  Trace []byte `thrift:"Trace,4" db:"Trace" json:"Trace,omitempty"`
}

func NewTRequest() *TRequest {
  return &TRequest{}
}

var TRequest_Type_DEFAULT int32
func (p *TRequest) GetType() int32 {
  if !p.IsSetType() {
    return TRequest_Type_DEFAULT
  }
return *p.Type
}
var TRequest_Content_DEFAULT []byte

func (p *TRequest) GetContent() []byte {
  return p.Content
}
var TRequest_ShardingId_DEFAULT int64
func (p *TRequest) GetShardingId() int64 {
  if !p.IsSetShardingId() {
    return TRequest_ShardingId_DEFAULT
  }
return *p.ShardingId
}
var TRequest_Trace_DEFAULT []byte

func (p *TRequest) GetTrace() []byte {
  return p.Trace
}
func (p *TRequest) IsSetType() bool {
  return p.Type != nil
}

func (p *TRequest) IsSetContent() bool {
  return p.Content != nil
}

func (p *TRequest) IsSetShardingId() bool {
  return p.ShardingId != nil
}

func (p *TRequest) IsSetTrace() bool {
  return p.Trace != nil
}

func (p *TRequest) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.I64 {
        if err := p.ReadField3(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 4:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField4(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TRequest)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.Type = &v
}
  return nil
}

func (p *TRequest)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Content = v
}
  return nil
}

func (p *TRequest)  ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(ctx); err != nil {
  return thrift.PrependError("error reading field 3: ", err)
} else {
  p.ShardingId = &v
}
  return nil
}

func (p *TRequest)  ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 4: ", err)
} else {
  p.Trace = v
}
  return nil
}

func (p *TRequest) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "TRequest"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
    if err := p.writeField3(ctx, oprot); err != nil { return err }
    if err := p.writeField4(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TRequest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetType() {
    if err := oprot.WriteFieldBegin(ctx, "Type", thrift.I32, 1); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:Type: ", p), err) }
    if err := oprot.WriteI32(ctx, int32(*p.Type)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.Type (1) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 1:Type: ", p), err) }
  }
  return err
}

func (p *TRequest) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetContent() {
    if err := oprot.WriteFieldBegin(ctx, "Content", thrift.STRING, 2); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:Content: ", p), err) }
    if err := oprot.WriteBinary(ctx, p.Content); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.Content (2) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 2:Content: ", p), err) }
  }
  return err
}

func (p *TRequest) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetShardingId() {
    if err := oprot.WriteFieldBegin(ctx, "ShardingId", thrift.I64, 3); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:ShardingId: ", p), err) }
    if err := oprot.WriteI64(ctx, int64(*p.ShardingId)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.ShardingId (3) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 3:ShardingId: ", p), err) }
  }
  return err
}

func (p *TRequest) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetTrace() {
    if err := oprot.WriteFieldBegin(ctx, "Trace", thrift.STRING, 4); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:Trace: ", p), err) }
    if err := oprot.WriteBinary(ctx, p.Trace); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.Trace (4) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 4:Trace: ", p), err) }
  }
  return err
}

func (p *TRequest) Equals(other *TRequest) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.Type != other.Type {
    if p.Type == nil || other.Type == nil {
      return false
    }
    if (*p.Type) != (*other.Type) { return false }
  }
  if bytes.Compare(p.Content, other.Content) != 0 { return false }
  if p.ShardingId != other.ShardingId {
    if p.ShardingId == nil || other.ShardingId == nil {
      return false
    }
    if (*p.ShardingId) != (*other.ShardingId) { return false }
  }
  if bytes.Compare(p.Trace, other.Trace) != 0 { return false }
  return true
}

func (p *TRequest) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TRequest(%+v)", *p)
}

// Attributes:
//  - ErrCode
//  - Type
//  - Content
//  - Trace
type TResponse struct {
  ErrCode *int64 `thrift:"ErrCode,1" db:"ErrCode" json:"ErrCode,omitempty"`
  Type *int32 `thrift:"Type,2" db:"Type" json:"Type,omitempty"`
  Content []byte `thrift:"Content,3" db:"Content" json:"Content,omitempty"`
  Trace []byte `thrift:"Trace,4" db:"Trace" json:"Trace,omitempty"`
}

func NewTResponse() *TResponse {
  return &TResponse{}
}

var TResponse_ErrCode_DEFAULT int64
func (p *TResponse) GetErrCode() int64 {
  if !p.IsSetErrCode() {
    return TResponse_ErrCode_DEFAULT
  }
return *p.ErrCode
}
var TResponse_Type_DEFAULT int32
func (p *TResponse) GetType() int32 {
  if !p.IsSetType() {
    return TResponse_Type_DEFAULT
  }
return *p.Type
}
var TResponse_Content_DEFAULT []byte

func (p *TResponse) GetContent() []byte {
  return p.Content
}
var TResponse_Trace_DEFAULT []byte

func (p *TResponse) GetTrace() []byte {
  return p.Trace
}
func (p *TResponse) IsSetErrCode() bool {
  return p.ErrCode != nil
}

func (p *TResponse) IsSetType() bool {
  return p.Type != nil
}

func (p *TResponse) IsSetContent() bool {
  return p.Content != nil
}

func (p *TResponse) IsSetTrace() bool {
  return p.Trace != nil
}

func (p *TResponse) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.I64 {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.I32 {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 3:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField3(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 4:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField4(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TResponse)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(ctx); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.ErrCode = &v
}
  return nil
}

func (p *TResponse)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Type = &v
}
  return nil
}

func (p *TResponse)  ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 3: ", err)
} else {
  p.Content = v
}
  return nil
}

func (p *TResponse)  ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadBinary(ctx); err != nil {
  return thrift.PrependError("error reading field 4: ", err)
} else {
  p.Trace = v
}
  return nil
}

func (p *TResponse) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "TResponse"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
    if err := p.writeField3(ctx, oprot); err != nil { return err }
    if err := p.writeField4(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TResponse) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetErrCode() {
    if err := oprot.WriteFieldBegin(ctx, "ErrCode", thrift.I64, 1); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:ErrCode: ", p), err) }
    if err := oprot.WriteI64(ctx, int64(*p.ErrCode)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.ErrCode (1) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 1:ErrCode: ", p), err) }
  }
  return err
}

func (p *TResponse) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetType() {
    if err := oprot.WriteFieldBegin(ctx, "Type", thrift.I32, 2); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:Type: ", p), err) }
    if err := oprot.WriteI32(ctx, int32(*p.Type)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.Type (2) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 2:Type: ", p), err) }
  }
  return err
}

func (p *TResponse) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetContent() {
    if err := oprot.WriteFieldBegin(ctx, "Content", thrift.STRING, 3); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:Content: ", p), err) }
    if err := oprot.WriteBinary(ctx, p.Content); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.Content (3) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 3:Content: ", p), err) }
  }
  return err
}

func (p *TResponse) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetTrace() {
    if err := oprot.WriteFieldBegin(ctx, "Trace", thrift.STRING, 4); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:Trace: ", p), err) }
    if err := oprot.WriteBinary(ctx, p.Trace); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.Trace (4) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 4:Trace: ", p), err) }
  }
  return err
}

func (p *TResponse) Equals(other *TResponse) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if p.ErrCode != other.ErrCode {
    if p.ErrCode == nil || other.ErrCode == nil {
      return false
    }
    if (*p.ErrCode) != (*other.ErrCode) { return false }
  }
  if p.Type != other.Type {
    if p.Type == nil || other.Type == nil {
      return false
    }
    if (*p.Type) != (*other.Type) { return false }
  }
  if bytes.Compare(p.Content, other.Content) != 0 { return false }
  if bytes.Compare(p.Trace, other.Trace) != 0 { return false }
  return true
}

func (p *TResponse) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TResponse(%+v)", *p)
}

type TService interface {
  // Parameters:
  //  - Req
  TwoWay(ctx context.Context, req *TRequest) (_r *TResponse, _err error)
  // Parameters:
  //  - Req
  OneWay(ctx context.Context, req *TRequest) (_err error)
}

type TServiceClient struct {
  c thrift.TClient
  meta thrift.ResponseMeta
}

func NewTServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *TServiceClient {
  return &TServiceClient{
    c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
  }
}

func NewTServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *TServiceClient {
  return &TServiceClient{
    c: thrift.NewTStandardClient(iprot, oprot),
  }
}

func NewTServiceClient(c thrift.TClient) *TServiceClient {
  return &TServiceClient{
    c: c,
  }
}

func (p *TServiceClient) Client_() thrift.TClient {
  return p.c
}

func (p *TServiceClient) LastResponseMeta_() thrift.ResponseMeta {
  return p.meta
}

func (p *TServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
  p.meta = meta
}

// Parameters:
//  - Req
func (p *TServiceClient) TwoWay(ctx context.Context, req *TRequest) (_r *TResponse, _err error) {
  var _args0 TServiceTwoWayArgs
  _args0.Req = req
  var _result2 TServiceTwoWayResult
  var _meta1 thrift.ResponseMeta
  _meta1, _err = p.Client_().Call(ctx, "twoWay", &_args0, &_result2)
  p.SetLastResponseMeta_(_meta1)
  if _err != nil {
    return
  }
  return _result2.GetSuccess(), nil
}

// Parameters:
//  - Req
func (p *TServiceClient) OneWay(ctx context.Context, req *TRequest) (_err error) {
  var _args3 TServiceOneWayArgs
  _args3.Req = req
  p.SetLastResponseMeta_(thrift.ResponseMeta{})
  if _, err := p.Client_().Call(ctx, "oneWay", &_args3, nil); err != nil {
    return err
  }
  return nil
}

type TServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler TService
}

func (p *TServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *TServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *TServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewTServiceProcessor(handler TService) *TServiceProcessor {

  self4 := &TServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self4.processorMap["twoWay"] = &tServiceProcessorTwoWay{handler:handler}
  self4.processorMap["oneWay"] = &tServiceProcessorOneWay{handler:handler}
return self4
}

func (p *TServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
  if err2 != nil { return false, thrift.WrapTException(err2) }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(ctx, seqId, iprot, oprot)
  }
  iprot.Skip(ctx, thrift.STRUCT)
  iprot.ReadMessageEnd(ctx)
  x5 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
  x5.Write(ctx, oprot)
  oprot.WriteMessageEnd(ctx)
  oprot.Flush(ctx)
  return false, x5

}

type tServiceProcessorTwoWay struct {
  handler TService
}

func (p *tServiceProcessorTwoWay) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := TServiceTwoWayArgs{}
  var err2 error
  if err2 = args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
    oprot.WriteMessageBegin(ctx, "twoWay", thrift.EXCEPTION, seqId)
    x.Write(ctx, oprot)
    oprot.WriteMessageEnd(ctx)
    oprot.Flush(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  // Start a goroutine to do server side connectivity check.
  if thrift.ServerConnectivityCheckInterval > 0 {
    var cancel context.CancelFunc
    ctx, cancel = context.WithCancel(ctx)
    defer cancel()
    var tickerCtx context.Context
    tickerCtx, tickerCancel = context.WithCancel(context.Background())
    defer tickerCancel()
    go func(ctx context.Context, cancel context.CancelFunc) {
      ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
      defer ticker.Stop()
      for {
        select {
        case <-ctx.Done():
          return
        case <-ticker.C:
          if !iprot.Transport().IsOpen() {
            cancel()
            return
          }
        }
      }
    }(tickerCtx, cancel)
  }

  result := TServiceTwoWayResult{}
  var retval *TResponse
  if retval, err2 = p.handler.TwoWay(ctx, args.Req); err2 != nil {
    tickerCancel()
    if err2 == thrift.ErrAbandonRequest {
      return false, thrift.WrapTException(err2)
    }
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing twoWay: " + err2.Error())
    oprot.WriteMessageBegin(ctx, "twoWay", thrift.EXCEPTION, seqId)
    x.Write(ctx, oprot)
    oprot.WriteMessageEnd(ctx)
    oprot.Flush(ctx)
    return true, thrift.WrapTException(err2)
  } else {
    result.Success = retval
  }
  tickerCancel()
  if err2 = oprot.WriteMessageBegin(ctx, "twoWay", thrift.REPLY, seqId); err2 != nil {
    err = thrift.WrapTException(err2)
  }
  if err2 = result.Write(ctx, oprot); err == nil && err2 != nil {
    err = thrift.WrapTException(err2)
  }
  if err2 = oprot.WriteMessageEnd(ctx); err == nil && err2 != nil {
    err = thrift.WrapTException(err2)
  }
  if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
    err = thrift.WrapTException(err2)
  }
  if err != nil {
    return
  }
  return true, err
}

type tServiceProcessorOneWay struct {
  handler TService
}

func (p *tServiceProcessorOneWay) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := TServiceOneWayArgs{}
  var err2 error
  if err2 = args.Read(ctx, iprot); err2 != nil {
    iprot.ReadMessageEnd(ctx)
    return false, thrift.WrapTException(err2)
  }
  iprot.ReadMessageEnd(ctx)

  tickerCancel := func() {}
  _ = tickerCancel

  if err2 = p.handler.OneWay(ctx, args.Req); err2 != nil {
    tickerCancel()
    return true, thrift.WrapTException(err2)
  }
  tickerCancel()
  return true, nil
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Req
type TServiceTwoWayArgs struct {
  Req *TRequest `thrift:"req,1" db:"req" json:"req"`
}

func NewTServiceTwoWayArgs() *TServiceTwoWayArgs {
  return &TServiceTwoWayArgs{}
}

var TServiceTwoWayArgs_Req_DEFAULT *TRequest
func (p *TServiceTwoWayArgs) GetReq() *TRequest {
  if !p.IsSetReq() {
    return TServiceTwoWayArgs_Req_DEFAULT
  }
return p.Req
}
func (p *TServiceTwoWayArgs) IsSetReq() bool {
  return p.Req != nil
}

func (p *TServiceTwoWayArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TServiceTwoWayArgs)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.Req = &TRequest{}
  if err := p.Req.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Req), err)
  }
  return nil
}

func (p *TServiceTwoWayArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "twoWay_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TServiceTwoWayArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "req", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:req: ", p), err) }
  if err := p.Req.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Req), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:req: ", p), err) }
  return err
}

func (p *TServiceTwoWayArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TServiceTwoWayArgs(%+v)", *p)
}

// Attributes:
//  - Success
type TServiceTwoWayResult struct {
  Success *TResponse `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewTServiceTwoWayResult() *TServiceTwoWayResult {
  return &TServiceTwoWayResult{}
}

var TServiceTwoWayResult_Success_DEFAULT *TResponse
func (p *TServiceTwoWayResult) GetSuccess() *TResponse {
  if !p.IsSetSuccess() {
    return TServiceTwoWayResult_Success_DEFAULT
  }
return p.Success
}
func (p *TServiceTwoWayResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *TServiceTwoWayResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField0(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TServiceTwoWayResult)  ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
  p.Success = &TResponse{}
  if err := p.Success.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
  }
  return nil
}

func (p *TServiceTwoWayResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "twoWay_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TServiceTwoWayResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := p.Success.Write(ctx, oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
    }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *TServiceTwoWayResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TServiceTwoWayResult(%+v)", *p)
}

// Attributes:
//  - Req
type TServiceOneWayArgs struct {
  Req *TRequest `thrift:"req,1" db:"req" json:"req"`
}

func NewTServiceOneWayArgs() *TServiceOneWayArgs {
  return &TServiceOneWayArgs{}
}

var TServiceOneWayArgs_Req_DEFAULT *TRequest
func (p *TServiceOneWayArgs) GetReq() *TRequest {
  if !p.IsSetReq() {
    return TServiceOneWayArgs_Req_DEFAULT
  }
return p.Req
}
func (p *TServiceOneWayArgs) IsSetReq() bool {
  return p.Req != nil
}

func (p *TServiceOneWayArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.STRUCT {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *TServiceOneWayArgs)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  p.Req = &TRequest{}
  if err := p.Req.Read(ctx, iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Req), err)
  }
  return nil
}

func (p *TServiceOneWayArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "oneWay_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *TServiceOneWayArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "req", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:req: ", p), err) }
  if err := p.Req.Write(ctx, oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Req), err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:req: ", p), err) }
  return err
}

func (p *TServiceOneWayArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("TServiceOneWayArgs(%+v)", *p)
}


